name: Dependabot Approve
on:
  workflow_call:

permissions:
  pull-requests: write

# TODO: move jobs here
jobs:
  dependabot_check:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Dependabot check
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('PR author is not dependabot[bot]')

# automerge_dependabot:
#   runs-on: ubuntu-latest
#   needs: [build]
#   # failing this will skip this step - not fail the build
#   if: ${{ github.actor == 'dependabot[bot]' }}
#   uses: tstapleton/jira-cards/.github/workflows/dependabot-approve.yml@tst/gha-2
