name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Download dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  check-dependabot:
    runs-on: ubuntu-latest
    needs: [build]
    # TODO: should be ==
    # failing this will skip this step - not fail the build
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run dependabot approve workflow
        uses: tstapleton/jira-cards/.github/workflows/dependabot-approve.yml@tst/gha-2
